services:
  analysis-env:
    image: ttimbers/breast_cancer_predictor_py:d285fc9
    ports:
      - "8888:8888"
    volumes:
      - .:/home/wildfire
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64
