services:
  analysis-env:
    image: brarstar14/forest-fire-container:latest
    ports:
      - "8888:8888"
    volumes:
      - .:/home/wildfire
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64
